// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX45fBSYvU6PEiriUVMBXT1sLqLj6KuU4',
    appId: '1:1063266481481:web:d0413d8a14fdd6bc25d698',
    messagingSenderId: '1063266481481',
    projectId: 'analytics-dashboard-6e151',
    authDomain: 'analytics-dashboard-6e151.firebaseapp.com',
    storageBucket: 'analytics-dashboard-6e151.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Hwi9jdnSErXFF2bFfMbmQ_u84X0nz4A',
    appId: '1:1063266481481:android:931f0143ed1cdcab25d698',
    messagingSenderId: '1063266481481',
    projectId: 'analytics-dashboard-6e151',
    storageBucket: 'analytics-dashboard-6e151.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUGHlHjTvtJdi5MYNwoUOD_UOylseiaKM',
    appId: '1:1063266481481:ios:1ec7d1a0e30d532925d698',
    messagingSenderId: '1063266481481',
    projectId: 'analytics-dashboard-6e151',
    storageBucket: 'analytics-dashboard-6e151.firebasestorage.app',
    iosBundleId: 'com.example.webDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUGHlHjTvtJdi5MYNwoUOD_UOylseiaKM',
    appId: '1:1063266481481:ios:1ec7d1a0e30d532925d698',
    messagingSenderId: '1063266481481',
    projectId: 'analytics-dashboard-6e151',
    storageBucket: 'analytics-dashboard-6e151.firebasestorage.app',
    iosBundleId: 'com.example.webDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX45fBSYvU6PEiriUVMBXT1sLqLj6KuU4',
    appId: '1:1063266481481:web:a73019e80a80527a25d698',
    messagingSenderId: '1063266481481',
    projectId: 'analytics-dashboard-6e151',
    authDomain: 'analytics-dashboard-6e151.firebaseapp.com',
    storageBucket: 'analytics-dashboard-6e151.firebasestorage.app',
  );
}
